services:
  postgres:
    image: postgres:15
    container_name: codearena_build
    environment:
      POSTGRES_DB: codearena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mdarbaz77
    ports:
      - "5433:5432"
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  codearena_db_data:
